### ISSUE TITLE
The result value of a complex value copy is wrong

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#123]
In the following code, the return value of the assignment on the last line will be `0`, and be of type `uint16`.

```
class Point::
    x, y: uint32
Point p, q: 10, 20
p = q
```

The reason for this is that because below the surface, the `type::copy` function is called, which has `uint16` as return type. A zero-code means a successful copy. To return `0` doesn't make a lot of sense language wise however.

The return value should be `q` here.

**Comment by jleeothon** [comment]
What does it mean "complex" here?
Do you mean the return value of the assignment operation should be a reference to `q` (or `p` which are now the same)?

**Comment by SanderMertens** [comment]
Complex, as in non-primitive values.

**Comment by SanderMertens** [comment]
Issues with the scripting language are postponed.
