### ISSUE TITLE
Write specification for annotations for bindings

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#132]
Cortex needs a piece of syntax that supports annotations. Two main use cases are:

- Documenting objects. This documentation can be taken advantage of with a future `man` command in `cxsh` as suggested by @SanderMertens. Also, the HTML generator could leverage from this.
- Overriding or disambiguating pieces of code that are hard to provide binding for, as exemplified in #131.

**Comment by SanderMertens** [comment]
This is a duplicate of #169
