### ISSUE TITLE
Standardize existing test suites

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#145]
Currently the architecture of `tc_jsonser` and `tc_iterator` are fairly different. For instance:
- `tc_jsonser`compiles to a package; `tc_iterator` compiles to an executable.
- the `main` function is in `tc_jsonser.c`; the `main` function is in `tc_iterator__load.c`.

The approaches found in iterator tests cases seem more desirable as of now, but they need a bigger redesign along with #45.

**Comment by jleeothon** [comment]
I believe that some significant part of this discussion is not relevant anymore since we now have a test automation framework.

Before, we had:
- custom corto scripts and a shell script to collect results (core)
- as mentioned herefore, custom packages
- as mentioned herefore, custom components.

Maybe the part of this discussion left is the matter of which parts of the Corto framework cannot be covered by unit testing with ::corto::test.

**Comment by jleeothon** [comment]
We should port the previous tests to the new test framework nevertheless.

**Comment by SanderMertens** [comment]
This has been done for some time now!
