### ISSUE TITLE
Generators should be able to remove files that it wouldn't have created

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#154]
Supposed we generate documentation for a class, then we remove a member. If we regenerate documentation, the docs for the dead member will still be there.

Similar problems happen with other e.g. the C generator and generated class bindings.

**Comment by jleeothon** [comment]
There should be an option for `cxgen` that cleans these files, and `make clean` calls it.

**Comment by SanderMertens** [comment]
I've decided to not remove the files, but instead print a warning and rename the file to <filename>.old

That will prevent accidental loss of source code when for example a user renames a class.
