### ISSUE TITLE
Min/max values are not correctly represented in the type system 

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#215]
The min & max values for integers are represented using 64 bit integers. The min and max values are not always for 64 bit integers though, they can be for 8, 16 or 32 bit as well.

The current values in the intX classes do not properly take this into account.

**Comment by jleeothon** [comment]
Why is this an issue?

**Comment by SanderMertens** [comment]
Attached screenshot demonstrates the issue. It only happens for unsigned ints. This is likely caused by an incorrect value in the cx__bootstrap.h. 

<img width="799" alt="screen shot 2015-07-15 at 11 36 03 am" src="https://cloud.githubusercontent.com/assets/9919222/8702457/df20afa4-2ae5-11e5-8e3c-2155a26a40e4.png">

**Comment by jleeothon** [comment]
I checked other types. It also looks weird in non uinteger's.
<img width="651" alt="screen shot 2015-07-15 at 13 32 04" src="https://cloud.githubusercontent.com/assets/6202537/8706757/14e3126a-2af7-11e5-8909-40d7ab40b576.png">

What if we represented ints' max/min with int64 and uints' with uint64?
