### ISSUE TITLE
const qualifier is missing in many API methods

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#218]
The const modifier is missing in many API methods. There are many examples, including:
1. I have (const) char pointers in the sqlite connector.
2. These are forwarded to the dependency algorithm. The dependency algorithm doesn't have const qualifiers to its `void *dependents` and `void *dependencies`. If I try to add them here, I run into:
3. Functions like cx_nameof do not include the qualifier in their signature either.

The `const` qualifier is regarded as a good practice of contract; adding it may increase usability as the compiler will complain less about "discarding const qualifiers".

**Comment by SanderMertens** [comment]
I agree it's a good practice, however you'll encounter some trouble when you want to fix it. Because strings often use the type cx_string, you can't put const before it. Unfortunately
```
const char* str
```
is different from
```
typedef char* string;
const string str;
```

Until the type system properly recognizes const, this will be painful to address.

**Comment by SanderMertens** [comment]
Const has been consistently applied in core API functions. The typesystem still does not recognize const for function parameters, so there `corto_string` is still used.
