### ISSUE TITLE
TestCase shouldn't hold the result of an execution

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#255]
Currently, the creation of a `TestCase` executes a function therewithin and holds itself the result. But this is not appropriate because the `TestCase` is the definition of a series of test methods, and yet an instance thereof has the results of a single one of those methods.

Think about it. You have a `MyTestCase` instance. It has many methods. Only one was executed. The rest of the methods don't mean anything else after. You have several MyTestCase instances and each executed a method of the class's scope.

Instead, let the `TestCase` be the definition of methods with common `fixture`, `setUp`, `tearDown`. We can have another class or struct that relates a test method (and therefore, its test case, fixture, etc.) and its result. We can call this one a `TestRun` or a `TestExecution`. *A test run is the relation between a test method and the result of running it.* (Not sure if these terminology is canonical enough). The (data centric :wink:) definition of a `TestRun` executes the test-case-under-execution's set up, the test method in question, and tear down.

**Comment by jleeothon** [comment]
To separate these doesn't prove as easy. To make test methods and asserts as dry as possible, assertions will have to alter an instance member of the test case's; then the test run will be able to get the result (otherwise, the assertion and test method would have to return values to be caught by the user).

Then this result is copied by the test execution, e.g. to persist.

**Comment by jleeothon** [comment]
Reading about the xUnit architecture and the PyUnit implementation, the Test Runner collects results from the Test Cases based on exception throwing. However, because we don't have exceptions in Cortex, we can't use these to decouple them.

**Comment by SanderMertens** [comment]
This issue has been fixed when we made the decision to execute each method in its own process.
