### ISSUE TITLE
Test method should stop executing when an assertion fails

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#256]
Tests continue executing even when an assertion fail. As a result, any next assertion (however undesirable it is to use multiple assertions per test) may change the test result and the original error becomes hidden.

**Comment by SanderMertens** [comment]
Why does a 2nd assertion hide the first assertion?

**Comment by jleeothon** [comment]
The second assertion would hide the first assertion because in test_TestCase:

```
static cx_void test_TestCase_test(test_TestCase _this, cx_bool b, cx_string assertmsg, cx_string errmsg) {
    if (!b) {
        // etc
    } 
```

The result's success, assertmsg and errmsg would be rewritten upon any false assert condition.

To solve that, the condition should be changed to:

```
if (_this->result.success && !b) {}
```

**Comment by jleeothon** [comment]
To prevent lines of code following a failing assertion from being executed, we could add in `test_TestCase` a set of macros to exit the test method.

Let's remember that both assertion methods and test methods are of void type. We need to keep test methods void, and make assertion methods return 0 on success.

Then we can define something like:


```
// test_TestCase.c

/* $header() */
#define test_TestCase_assert_bool(_this,b) if(test_TestCase_assert_bool((_this),(b)){return;}
/* $end */

/* ::cortex::test::TestCase::assert(bool b) */
cx_bool test_TestCase_assert_bool(test_TestCase _this, cx_bool b) {
/* $begin(::cortex::test::TestCase::assert(bool b)) */
    // blah blah
/* $end */
}
```

**Comment by SanderMertens** [comment]
This is addressed.
