### ISSUE TITLE
Profiling framework

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#261]
There is need for a profiling framework.

The very basic need it should address is providing a start and stop methods. At stop, a time delta value should become known. Also, time deltas should be able to be stacked. E.g.

```
profiling_start() // A
profiling_start() // B
profiling stop() // B -> 3 seconds
profiling_start() // C
profiling_stop() // C -> 2 seconds
profiling_stop() // A -> 6 seconds
```

Note that any start-stop is equal to or bigger than the sum of any pair upper in the stack.

**Pending doubts**
- Do we need the profiler to be object-oriented?
- If not object oriented, then do we need thread-specific singletons? (see `async.c`)

**Comment by jleeothon** [comment]
This is a manual test I've used.

```
void foo():
    profiling::start("foo")
    profiling::stop()

int8 bar():
    profiling::start("bar")
    foo()
    profiling::stop()

struct Hello::
    member world: int16
    void chunky():
        profiling::start("chunky")
        this.bacon()
        int64 i = 100000
        while i > 0:
            i--
        profiling::stop()        
    string bacon():
        profiling::start("bacon")
        foo()
        foo()
        profiling::stop()

Hello hi: 6

foo()
bar()
bar()

hi.chunky()
hi.bacon()
```

Results are:

![screenshot 2015-06-21 11 28 41](https://cloud.githubusercontent.com/assets/6202537/8272455/c04656d2-1808-11e5-82d8-97f25cd2a982.png)
![screenshot 2015-06-21 11 28 53](https://cloud.githubusercontent.com/assets/6202537/8272454/c045109c-1808-11e5-9d19-2d61b3e918d8.png)

**Comment by SanderMertens** [comment]
The current profiling framework exists in `cortoproject/profile`. Further issues will be captured on that repository
