### ISSUE TITLE
Deserialize JSON into Cortex objects

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#280]
We need a JSON deserializer for Cortex objects, that is also useful to work along https://github.com/cortexlang/web. It needs to be compatible with JSON as produced by #16.

**Comment by jleeothon** [comment]
Note to self: serialization of `root_o` is:

```
{
    "meta": {
        "name": "::",
        "type": "::cortex::lang::package",
        "states": "V|DCL|DEF",
        "attributes": "S|O",
        "parent": "",
        "childCount": 3
    },
    "value": {
        "url": "http://cortexlang.com/"
    },
    "scope": [
        {
            "name": "cortex",
            "type": "::cortex::lang::package",
            "states": "V|DCL|DEF",
            "attributes": "S|O",
            "childCount": 6
        },
        {
            "name": "runner",
            "type": ": : cortex: : test: : Runner",
            "states": "V|DCL|DEF",
            "attributes": "S|W|O|P",
            "childCount": 0
        },
        {
            "name": "testjson",
            "type": ": : cortex: : lang: : package",
            "states": "V|DCL|DEF",
            "attributes": "S|W|O|P",
            "childCount": 4
        }
    ]
}
```

(The extra objects come from testing framework).

The serialization/deserialization of root's name and parent should be consistent in both ways.

**Comment by jleeothon** [comment]
For self reference, it occurs that
```
// 0x107bb8f80
printf("0 %p\n", root_o);

// NULL
cx_object o1 = cx_resolve(NULL, "");
printf("1 %p\n", o1);

// fails
// cx_object o2 = cx_resolve(NULL, NULL);
// printf("2 %p\n", o2);

// NULL
cx_object o3 = cx_parentof(root_o);
printf("3 %p\n", o3);

// (null)
cx_string rootname = cx_nameof(root_o);
printf("4 %s\n", rootname);

// ::
cx_id rootfullname;
cx_fullname(root_o, rootfullname);
printf("5 %s\n", rootfullname);
```

Therefore, it doesn't occur to me that `cx_resolve` would be able to resolve root in any way.

The following set of questions occurred to me:

- Should `cx_resolve` not be able to resolve root from itself?
    - Maybe not, since one can't resolve oneself from anywhere else.
- Should root be resolved as `"::"` as opposed to `null` or empty string?
    - Its name in C is `null` and other names (`meta.name`) are the individual name and not the fully scoped name.
    - However, it simplifies the format of the resulting JSON because now it's always a string instead of string-or-null.
    - Should it be empty string?
    - Take into account that both root and anonymous objects lack name and parent.}

In the end, maybe it *is* fine to use "::" as root's name since that's its full name, and it appears as such when serializing "parent" of objects in root scope.

I will just write the deserializer to get root when it sees "::" for the object name.

**Comment by SanderMertens** [comment]
JSON deserializer is implemented. Though not complete, it is usable. Subsequent issues shall address improving the current implementation.
