### ISSUE TITLE
Parser doesn't complain about passing initializers to reference parameters

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#296]
The following code:

``` c++
class Point:: x, y: int32

void func(Point p): "$p"

func({10, 20})
```

should issue an error since it will surely crash. The parser does no such thing.

**Comment by jleeothon** [comment]
Why is this wrong?

I think this is synonymous with "you should never pass anonymous objects as parameters". Is that right?

**Comment by SanderMertens** [comment]
```c++
func({10, 20})
```
doesn't create an anonymous object. If you'd want to pass an anonymous object to a function, you'd have to write:
```c++
func(Point{10, 20})
```
The first statement is an initializer that needs to be assigned to "something", in this case the function argument, which is a reference. It is akin to writing:
```c++
var Point p = {10, 20} // crash
```
where you should have written:
```c++
var Point p = Point{10, 20}
```
