### ISSUE TITLE
cx_declare walks through scope tree twice

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#301]
The `cx_declare` function, before it adds a new object to a scope, first checks whether an object with that name is already present in the scope, and if it is, whether it has the same type that is passed to the `cx_declare` function.

If the test passes, `cx_declare` inserts the object in the scope. Since the scope is a red black tree, This process means calling two relatively expensive operations (`hasKey` and `set`).

A new operation should be added to the tree that inserts a value only when the key did not yet exist, and when it did exist, it should return the existing value.

**Comment by jleeothon** [comment]
There isn't any commit attached here. @SanderMertens
