### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#307]
It is preferable that a user only need to run one thing in order to get Cortex running on their machines.

Let's start by making a script that:
- downloads the Cortex source files,
- compiles Cortex,
- copies the `cortex`, `cxgen`, and `cxsh` executables to `/usr/local/bin`.

**Comment by SanderMertens** [comment]
Note that after issue #304 has been addressed, only the cortex executable has to be copied.

**Comment by SanderMertens** [comment]
For reference:

<img width="553" alt="screen shot 2015-08-18 at 8 55 56 pm" src="https://cloud.githubusercontent.com/assets/9919222/9401469/d6b6bd16-479d-11e5-80a0-0767916ea57d.png">
