### ISSUE TITLE
Run each testcase in its own process

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#330]
To ensure greater separation between the execution of test cases, each test case should be run in its own process.

When invoking the tests for project `X`, one would type `corto test X`. This process will then discover the test cases available for `X` and spawn additional processes for each method, using `corto test X <test case id>`.

**Comment by SanderMertens** [comment]
Instead of using `corto test` for invoking a testcase, use `corto testcase`. In the event that >> something << goes wrong and data gets corrupted, this decreases the chances of creating a fork bomb (`corto test` invoking another `corto test` is potentially dangerous).

**Comment by SanderMertens** [comment]
Actually, it'd be more straightforward to just do `corto ./.corto/libtest.so <testcase>`.

**Comment by jleeothon** [comment]
+1!
