### ISSUE TITLE
cx_lookup fails with NULL

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#359]
`cx_lookup(NULL, name)` crashes, whereas `cx_resolve(NULL, name)` is idiomatic. Should this be considered a bug?
If we decide that `cx_lookup` shouldn't accept NULL for a first argument, we should still validate against it and print an error message instead of crashing.

<img width="1027" alt="screen shot 2015-09-30 at 00 48 53" src="https://cloud.githubusercontent.com/assets/6202537/10180407/32693b6e-670d-11e5-8fb7-54349475249e.png">

**Comment by SanderMertens** [comment]
I reconciled with `cx_resolve`. If you provide NULL, it will replace NULL with `root_o`.
