### ISSUE TITLE
Support for requested vs. actual parameters

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#361]
A common idiom in distributed data centric systems is using target and actual values. For example, a thermostat might have a target temperature of 72, and an actual temperature of 68. This could be accomplished in corto today, with a definition like this:

``` c++
struct Thermostat::
    targetTemperature: int32
    actualTemperature: int32, readonly
    on update this: // do something
```

The behavior of the above two variables is completely up to the user. The downside of the above is that semantics of this pattern might vary from package to package (or even class to class). Additionally, the framework does not know about the semantic relation between the members, which would rule out the possibility to take advantage of this knowledge in dashboards or language bindings.

Proposed to introduce a new feature that enables this behavior on a member:

``` c++
struct Thermostat::
    temperature: int32, request
    on update this: // do something
```

Semantics of this "request" field should be:

``` c++
Thermostat t: 70 // Set target temperature to 70
"The current temperature is ${t.temperature}" // By default, read the actual temperature
t.temperature = 80 // Set target temperature to 80
"The current target is ${t.temperature.target}" // Read out target temperature
```

The actual temperature should not be writable from outside the object's implementation, and should behave exactly like a readonly member.

**Comment by jleeothon** [comment]
It may result useful to understand what is the relationship between request members and normal public members, esp. when the current process is not owner of the object.

**Comment by SanderMertens** [comment]
Feature is implemented. Future changes / additions will be captured in new issues.
