### ISSUE TITLE
Move installation directory to /usr/local to fix issue with new version of OS X

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#365]
With the recent El Capitan release from OS X, users can no longer access the /usr folder, not even with root access rights. The installer currently installs files to this folder. For compatibility with OS X, move installation path to /usr/local.

**Comment by jleeothon** [comment]
Also, it wasn't possible to install on Cloud 9's VM. Maybe after this change, both will work.

<img width="576" alt="screen shot 2015-10-03 at 01 00 51" src="https://cloud.githubusercontent.com/assets/6202537/10261759/da34e17c-69a6-11e5-9e5f-2b8b2896337f.png">
