### ISSUE TITLE
test::Case as the default procedure type under TestSuite

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#367]
Just like global-level procedures are often of `function` type, and procedures in scope of `type`s are `method` by default, could it be possible to programmatically define the default type for procedures?

This way, we could legally make all methods under a `TestSuite` be `TestCase`s by default.

**Comment by SanderMertens** [comment]
For this we would have to do something fancy:

```
#package ::corto::test

procedure test::case : method

class Suite : class, defaultType = test::case
   ... // testsuite members
```

**Comment by SanderMertens** [comment]
Actually, I like this. A test definition would, instead like this:
```
class MySuite : test::suite ::
    void isPandaRed() test::case
    void isPandaBlue() test::Case
```
Look like this:
```
test::suite MySuite ::
    void isPandaRed()
    void isPandaBlue()
```
And in fact, it could even be shorter, since the signature of a testcase is predefined:
```
test::suite MySuite ::
    isPandaRed
    isPandaBlue
```
Or, for small test suites:
```
test::Suite MySuite :: isPandaRed, isPandaBlue
```

**Comment by jleeothon** [comment]
That is a very nice idea.

One extra precaution that I'd like to take is that the semi-complete syntax (that is `void isPandablue()`) should always be supported because the parentheses allow for parameters to be listed, which in the future will be useful for parametrized / data-driven tests. For example (tentative idea):

```C++
test::suite ListAddReducer::
    void testAddList(list numbers, int32 expectedResult)::
        test::parameters emptyList::
            list numbers{}
            int32 expectedResult: 0
        test::parameters normalList
            list numbers: 1, 2, 3, 4
            int32 expectedResult: 10
        test::parameteres listWithNegatives:
            list numbers: 4, -5, 11
            int32 expectedResult: 2
```

The downside of this, though, is that I don't think we right now support providing a *value* to a function as well as a *scope*. This could limit the Corto scripting language.

Another possible syntax for the above could be to use *annotations*  instead of *scopes* to provide parameters to a test.

In either case, parameters are important for the functions.

**Comment by SanderMertens** [comment]
Agree with all of the above. I think I should be able to extend the syntax to allow for function scopes without introducing conflicts.
