### ISSUE TITLE
Cannot successfully create and run application

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#374]
I had an almost fresh install (through corto.io's  curl | shell). Before installing, though, there were some files lingering in /usr/bin, /usr/include, /usr/lib from previous installs; remember that now, everything is in /usr/local.

corto create and corto run aren't successful:

<img width="591" alt="screen shot 2015-10-21 at 00 20 45" src="https://cloud.githubusercontent.com/assets/6202537/10622871/62f7d5be-778a-11e5-9148-0ba1a69455f8.png">

**Edit**: the files in /usr/bin were not correctly removed. This issue is no longer relevant.

**Comment by SanderMertens** [comment]
Please don't change your environment before understanding exactly what is going on. These scenarios might be hard to reproduce, and I want to be able to address them gracefully.

**Comment by jleeothon** [comment]
Self reference, the error backtraces as follows:

corto_project.c:78

```C
if (corto_create(
    8,
    (char*[]){"create", "package", "::test", "--empty", "--notest", "--local", "--silent", "--nobuild"}
)) {
    cx_error("corto: couldn't create test skeleton (check permissions)");
    goto error;
}
```

corto_project.c:475

```C
if (!strcmp(argv[1], CORTO_PACKAGE)) {
		if (corto_package(argc-1, &argv[1])) {
			goto error;
		}
```

`corto_setupProject` probably ran correctly (355, in `corto_package`).

**Comment by jleeothon** [comment]
In `cx_load` (cx_loader.c), we most probably hit line 254:

```C
if (!strcmp(ext, "cx")) {
        cx_load("corto::ast", 0, NULL);
```

The next place where it could've returned an error code would be:

```C
h = cx_lookupExt(ext);
    if (h) {
        /* Load file */
        lib = cx_fileAdminAdd(str);
        result = h->load(str, argc, argv, h->userData);
        lib->loading = FALSE;
```

wherein `h` is a file handler for cx files. The handler for cx files is registered in ast.c:261, `cx_loaderRegister("cx", fast_cortoRun, NULL);`.

**Comment by jleeothon** [comment]
The installation files were outdated. This issue is not relevant now.
