### ISSUE TITLE
Create local isolated environments

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#384]
# Intro

This is a proposal to create corto environments that are as isolated as possible between them.

An environment can be understood as a relation between a corto installation and sets of packages.
## Rationale

A developer needs to work on several projects at the same time on the same machine. Example projects:
- Project "A" depends on somePackage v1.0
- Project "B" depends on somePackage v2.0

When the developer wants to switch from working in one project to working with another project, one possible but undesirable solution could be:
1. I'm working on Project A, but I need to do a brief change to B.
2. Uninstall somePackage v1.0. E.g. `corto uninstall somePackage -v 1.0`
3. Install somePackage v2.0 because B needs that one. `corto install somePackage -v 2.0`.
4 Work on B.
5. Now let's go back to A. `corto install somePackage -v 1.0`

Now imagine that you have dozens of packages to depend on. Or that some packages aren't compatible between them. It's not a viable workflow.

Another less manual but still undesirable solution could be to clean the list of packages every time we need to "switch" context. This however consumes a lot of network and time. Also, the developer won't be able to open a shell with some personally preferred "global" set of packages. The packages installed will always depend on what's the last project that one worked with. 

The solution is to create **isolated environments** which store packages for themselves without interacting between them. In principle, one would use 1-1, one environment per project, but that can as well be just left up to the individual use cases.

The workflow thus becomes:
1. Need to start working on project A.
2. Create environment myenvA. `corto create env myenvA`.
3. `corto activate myenvA`. Install project A's dependencies. Work on A.
4. Need to start working on project B.
5. `corto deactivate` (deactivate myenvA).
6. Create environment myenvB. `corto create env myenvB`.
7. `corto activate myenvB`. Install project B's dependencies. Work on B.
8. Need to make a fix to A.
9. `corto deactivate` (deactivates myenvB).
10. `corto activate myenvA`.
11. Fix A.
12. :rocket: Keep rocking the world.

---

When an environment is "active":
- the `corto` command-line tool will refer to the environment's version of corto, regardless of which is the default version for a fresh terminal.
- any package downloaded by `corto install` will not be visible in the global installation (except if also installed when no "environment" is active), nor visible from other environments (except if also installed when the other environment was active).
## API

With the corto command, the following sub-commands would be added:
- `corto create env my-env corto=corto1.0`. The `create` command already exists and it's used for apps and packages and modules.
- `corto delete env my-env`. The `remove` command already exists but it's used for dependencies though. Maybe doesn't go along very well with `create`?
- `corto activate my-env`. Activates an existing environment. New command specific to environments.
- `corto deactivate`. New command specific to environments.
- `corto list env`. Lists all packages installed in an environment.
- `corto install` and `corto uninstall`. The same corto install that already exists, noting that it will only install in an environment when one is active (depending on implementation, this could be agnostic of whether or not an env is active).
## Implementation

Information about the environments shall live in $HOME/.corto.

Example:

```
$HOME
\-.corto/
  |
  |- include/
  |  \- corto/
  |     |-1.0/
  |     \-1.1/
  |- lib/
  |  \- corto/
  |     |-1.0/
  |     \-1.1/
  \- env/
     |-myapp_env/  <-- replicates the structure of $HOME/.corto without env/
     | |-include/
       | \-corto/
       |   \-1.0
       \-lib/
```

When an environment is active, $CORTO_HOME is overridden to point to `myapp_env/` instead of `$HOME/.corto`.

If everything else in Corto is wired relative to $CORTO_HOME, we should be able to use environments smoothly.
# Open questions
- From the spec above, it would sound possible to create, e.g. two environments myapp-1.0 and myapp-1.1. A user could run the app having any of two environments active, e.g. for testing how well it runs under each.
- If we find this architecture later unsuitable, it maybe hard to change only this part of the framework. Backwards compatibility would be a hard issue.
## How can we make `corto` resolve into the correct executable.

Modifying the PATH or creating a function would require `. corto blahblah` or `source`. in order to not create an extra isolated shell.

Needing the user `source` anything would be annoying.

Another possibility is to create a new shell with everything we need. The cons is that history between this shell and the parent shell will not be shared (big annoying bummer).

**Comment by SanderMertens** [comment]
Looks good. One comment about the command that you picked for removing an environment- a `create` is always paired up with a `delete`, whereas `add` is paired up with `remove`.

We had the discussion about cloud hosted environments before, which essentially means that we'll have multiple packages repositories for multiple environments (akin to the `cortoproject/packages` project). Therefore, we might want to have both the option to add & remove an environment from a machine, in addition to creating and deleting one. Example:

```bash
corto create env MyEnv # Create a new environment repo on GitHub
corto delete env MyEnv # Delete an environment repo on GitHub
corto add env MyEnv # Add an existing environment repo to my machine
corto remove env MyEnv # Remove an environment from my machine (don't delete it)
```

**Comment by SanderMertens** [comment]
At the moment, packages would have to be rebuilt for each environment, because binaries contain hard links to library locations. This is both good and bad- it really separates environments, but it also generates a lot of redundant load on build servers.

Ideally we have the capability to have environments "include" other environments. For example, I create an environment for my organization that only contains packages specific to my organization. I still however want to benefit from the Corto packages, so I'll also "include" the Corto environment.

To make that work without generating too much load, we need a tool that can "port" a binary from one environment to another, which essentially means rewiring the paths after a binary is created. I have read that this is possible on OS X, and I believe on Linux as well. Windows I am not sure.

This tool would be very useful in any case. We would be able to install Corto without requiring a users password and without "contaminating" `/usr/local`. That would be a good thing for users that just want test-drive Corto.

**Comment by SanderMertens** [comment]
Just out of curiosity, what would `corto activate` do exactly. Would it set the environment for the current shell, or more "persistently" for the machine? The latter would either require us to modify a file like `.bashrc` which is fishy, or we would have to store this information somewhere in a file.

**Comment by jleeothon** [comment]
Thanks for your comment on naming the commands. Note taken.

However, those are the "other" environments that we talked about outside GitHub. I just added a comment to reflect on the nature of what "isolated environment" means. This is jargon that's already in place with Python, Ruby and Node.

Environments are temporary. They live in a shell session; they do not persist in the computer. You do not need `sudo` to create or activate environments, nor to install packages in an isolated environment.

In Python+pip or Ruby+gems, you often need `sudo` to install packages *globally* but that is not the case with Corto if I'm not mistaken.

**Comment by jleeothon** [comment]
It could be nice if we could make corto hook onto `cd`, just like RVM (?) can activate an environment.
Zsh has a framework for that, and on bash, we can take a look at https://github.com/rcaloras/bash-preexec.

**Comment by SanderMertens** [comment]
The lines 141-144 of cortotool_environment.c are not working as expected:

```
/* TODO this parses the string into NULL */
corto_setenv("PS1", "($CORTO_ENVIRONMENT) $PS1", TRUE);
/* TODO this segfaults */
corto_setenv("PATH", "$CORTO_HOME:$PATH");
```

**Comment by SanderMertens** [comment]
This is a task spawning from #384.

If an environment with name e.g. env9 already exists, and one tries to create another, we get:

```
corto$ corto create env env9
ln: /Users/JohnnyLee/.corto/env/env9/bin/corto: File exists
could not execute script
```

Instead of complaining about a file that exists already, it should mention explicitly "An environment with this name already exists".

**Comment by SanderMertens** [comment]
Some manual string construction had to be done in `corto activate` because corto_setenv was buggy. Now we can rewrite it with corto_setenv.

**Comment by SanderMertens** [comment]
I'm going to close this issue, as I believe we have this capability today be it in a slightly different form. By setting the `$CORTO_TARGET` (where to build to) and `$CORTO_HOME` (where is corto) environment variables, a user can take full control over which environment he is working in. A common configuration would be to set `$CORTO_TARGET` to a location with custom packages, where `$CORTO_HOME` contains the core corto packages.
