### ISSUE TITLE
Fix installation issue on Debian

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#398]
`uname -p` produces a wide range of results on various platforms, which causes the installer to fail on Debian. To determine what architecture the operating system is using, `uname -m` is a more consistent alternative.

This will affect the cortoproject/packages repository since it will change the OS X installation location as well. This can best be solved together with issue #391

**Comment by jleeothon** [comment]
This was an issue since we based the code on the Meteor installer, wherein `uname -p`  was claimed to help offer support on OS X 10.6--an already very outdated OS. We probably do not need to support it. Moreover, `uname -p` is a GNU extension and not POSIX.
