### ISSUE TITLE
corto create env should complain about existing environments

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#400]
This is a task spawning from #384.

If an environment with name e.g. env9 already exists, and one tries to create another, we get:

```
corto$ corto create env env9
ln: /Users/JohnnyLee/.corto/env/env9/bin/corto: File exists
could not execute script
```

Instead of complaining about a file that exists already, it should mention explicitly "An environment with this name already exists".

**Comment by SanderMertens** [comment]
A simple `corto_fileTest()` should be able to resolve this issue.

**Comment by SanderMertens** [comment]
Moving this as comment to #384
