### ISSUE TITLE
Should corto_envparse() return NULL when it cannot find an environment variable

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#412]
Currently if we call something like ``corto_envparse("SOME_VAR", "1, 2, $THIS_DOESNT_EXIST")``, the call will return NULL. We could consider returning ``"1, 2 "`` instead, though, that could potentially hide logic errors. I'm writing this down so that it becomes a conscious decision.

**Comment by SanderMertens** [comment]
This is a conscious decision. corto_envparse will invoke the corto_seterr function which will give more details about the error (corto_env.c:74).
