### ISSUE TITLE
Spread changes in naming of corto_claim and corto_release

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#420]
There are some remnants of `cx_keep` (now `corto_claim`) and `cx_free` (now `corto_release`):

- `CORTO_TRACE_KEEP` and `CORTO_TRACE_FREE`
- strings literals e.g. `"keep %s of type %s -> %d (cycles=%d, source=%p, context='%s')"`, and `"free (%p)%s of type %s -> %d (cycles=%d, valid=%d, destructed = %d, source=%p, context='%s')"`

**Comment by SanderMertens** [comment]
Removed the documentation and QA labels. Documentation is meant for issues related to the documentation framework. QA is for issues related to test framework, tracking code coverage, reviewing code etc.
