### ISSUE TITLE
corto_assert may delete lines from compilation

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#430]
err.h defines corto_assert depending whether we do release or debug build, i.e.

```
#ifndef NDEBUG
#define corto_assert(condition, ...) if (!(condition)){_corto_assert(condition, "(" #condition ") " __VA_ARGS__);}
#else
#define corto_assert(condition, ...)
#endif
```

When NDEBUG is not defined, the `condition` is not evaluated altogether. In cases where the user may run a statement or function with side effects (e.g. `+=` or shortcut operators), then the debug and release build would not only differ in checking assertions, but also have different logic.

Another effect of the above definition is that variables that do only appear used in the assertion would provoke an "unused variable" warning. For release builds, where the assertion is not made, the compiler should be smart enough to ignore those variables (?).

Both problems can be solved by a void cast, i.e. 
```
#else
#define corto_assert(condition, ...) (void)(condition)
#endif
```

**Comment by SanderMertens** [comment]
Closing the issue, as issue seems fixed & I'm releasing 0.2.10
