### ISSUE TITLE
Application packaging / deployment

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#433]
A user should be able to package and deploy an application, much like a package. Some additional considerations apply to packaging an application.

 * Deployment should be super easy. A user of the application should ideally be able to install the application with a single command. This means that both corto library and packages that the application depends on should be statically linked (or at least a user should have the option to do so).
 * Another option would be to integrate with docker, and create an image that contain all dependencies for the application automatically
 * An application might rely on 3rd party frameworks / resources that potentially need to be initialized / started when the application is started. Ideally a deployment framework allows for specifying a script that is executed before the application is run (and perhaps after the application exits as well).
 * As an extra, it would be nice if the deployed application exposes statistics about itself over REST / ...

**Comment by jleeothon** [comment]
Docker can make it a bit easier for an application to expose an address+port.

**Comment by SanderMertens** [comment]
Applications and packages will be unified. Installing an application will be the same as installing a package (corto install).

Application deployment will be handled by a separate issue.
