### ISSUE TITLE
Error and exception handling

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#440]
# Current error handling

In the Corto codebase, error handling is mostly done by `corto_seterr`. When an error is produced, the code usually takes the form of:
1. Checking for a condition e.g. `if (!success)`.
2. Jumping to the end of the function with a `goto` statement. Some cleanup can be done immediately before, i.e. mostly freeing memory.
3. Sometimes cleanup can happen after the error label. This can reduce clutter.

We can tell apart two basic types of error handling structures: for "new" errors, and for "existing" errors. New errors occur when the current piece of code decides that an error has been produced. Existing errors are received by functions calling other functions, and determining that the subroutine has failed. `corto_seterr` should normally only be called when new errors are produced.

For example:

```
// new error
int function1() {
    ...
    if (a != b) {
        corto_seterr("something went wrong");
        goto error;
    }
    ...
    return 0;
error:
    corto_dealloc(x);
    return -1;
}

// old error
int function2() {
    if (function1()) {
        goto error; // corto_seterr not called here
    }
    return 0;
error:
    return -1;
}
```
# Exception handling

We can extend the pattern above to implement exception handling.

Room for ideas:
- All generated functions are wrapped around a macro for automatic casts. We can use this to add code related to exception handling, e.g. capturing the stack trace. Let's be careful not to supersize generated binaries.
- `#define corto_throw()` to automatically check for errors. Some universal variable can tell us whether there is an error has been produced (`corto_lasterr`, maybe). This can reduce the 3-liner (if-goto-closebracket) that should wrap around virtually every function call—three lines per every function call is a lot of clutter.
- `#define corto_catch()`
- corto_throw or corto_catch can default to an `error` label, but there are examples where more than one error label is necessary—especially when there are many pointers to deallocate in case of error.
- The outermost program loop could potentially detect exceptions being "raised" when an error has been set. It means that somewhere down the stack, an error was set. The above pattern forces every function to stop all execution (except freeing memory), so that the virtual machine can decide what to do, e.g. print stack trace.

Some caveats though:
- Corto functions and core functions have different signatures. They don't always return 0 for success and -1 for failure.
- We haven't been using the pattern thereby described consistently across the codebase.
  - We used to do `corto_error` instead of `corto_seterr`.
  - There wasn't  a clear distinction between "new" and "old" errors.
- We may need a special error-setting function for memory outages. When memory is scarce, it is likely that `corto_seterr` would fail to format-print the provided string into a buffer (TODO double check this fact). Therefore, we would use a static string instead.
# Other
## Goto macros

When calling functions, we often want to check for a condition (e.g. did it return null) and then `goto` an error label. Since this is such a common condition (we basically should do it every time we call a failable function), it would be nice to change the 3-liner for a 1-liner, e.g.

Take:

```
a = function();
if (a == -1) {
    goto error;
}
b = SomeClassCreate();
if (b == NULL) {
    goto error;
}
```

Now consider:

```
a = function();
corto_goto_if(a == -1, error);
b = SomeClassCreate();
corto_goto_unless(b, error);
```

An implementation of those macros would look like:
# define corto_goto_if(expr, label) do { if (expr) goto label; } while (0)
# define corto_goto_unless(expr, label) do { if (!(expr)) goto label; } while (0)

A name better than `corto_goto_if` or `corto_goto_unless` is welcome. Some alternatives:
- `corto_gotoif` and `corto_gotoifn`
- `corto_throw_if` and `corto_throw_ifn`
- reverse the order of "expr" and "label" so that it matches the order of "goto" and "if"; or reverse order of "goto" and "if".

I would advise against "catch" because "catch" suggests that an error is handled and the global error variable cleared. Instead, what we do is detect and error and interrupt the rest of the flow so that the virtual machine can go all the way up to the .
## Catch

In order to clear the global error we use corto_seterr(NULL).

If there's further instructions that need to be written along, we could wrap this pattern in a corto_catch macro. For example, if we want to _both_ check for an error and clear the error global.

Consider:

```
#define corto_catch() do { if (corto_lasterr()) corto_seterr(NULL) } while (0)
```

Are we concerned about the performance cost of corto_lasterr?
# Notes

About the do-while macros: http://stackoverflow.com/questions/1067226/c-multi-line-macro-do-while0-vs-scope-block

**Comment by SanderMertens** [comment]
The current logging framework has evolved to handle throw/catch like behavior in a way that works in a C context without having to rely on custom macro's. I'm in favor of this approach, as the code still looks like C-code. 

Currently, we do `corto_seterr` to "throw" an error. This error can be "catched" with `corto_lasterr` which returns the last thrown error as a string- which allows for chaining of error messages. If `corto_seterr` is called before the previous error has been retrieved with `corto_lasterr`, the framework will report an uncatched error to the console.

Future extensions to the framework could include exception objects, but that should be captured on a different issue.
