### ISSUE TITLE
Pre & Post Build Commands

### ISSUE THREAD

**Issue by hendrenja** [cortoproject/corto#442]
It would be useful if users could specify Pre & Post build commands in the rakefile. Commands should be captured as ["shell command 1", "shell command 2"]. 

Use:
PostBuildCommand = [package_deb.sh] // Runs shell script to create debian package from corto artifacts.

**Comment by SanderMertens** [comment]
You can use the prebuild and postbuild tasks for that:

```ruby
task :mypre do
    print "Run before build\n"
end


task :mypost do
    print "Run after build\n"
end

task :prebuild => [:mypre]
task :postbuild => [:mypost]
```

**Comment by SanderMertens** [comment]
For knowledge sharing, could you ask post this question on the forum as well? Thanks!
