### ISSUE TITLE
Add feature for uninstalling packages

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#444]
A user should be able to uninstall installed packages by doing
```
corto uninstall corto/web
```
This should delete all versions of a package (see #443).

Additionally, if a user does
```
corto uninstall corto/web:0.1.0
```
Only version 0.1.0 should be uninstalled.

The uninstaller always has to ensure that when there are still other versions installed that the links on the system point to the latest available version.

Also, the uninstaller should take care of removing all third party files that were installed as part of the package (version).

**Comment by jleeothon** [comment]
Can you be more specific or provide examples of what is a third-party file? I am guessing you mean things apart from the shared object files and header files. Is that e.g. files in /usr/local/etc?

**Comment by SanderMertens** [comment]
Yes, that is correct. Also, because of #445 files can also reside in `/usr/local/lib` or `/usr/local/bin`.
