### ISSUE TITLE
Linux-unknown being used by corto install in debian

### ISSUE THREAD

**Issue by foreverska** [cortoproject/corto#447]
Ruby scripts in build/ use uname -p in a few places.  Uname -p appears to be inconsistent across platforms and causes issues in my debian enviroment where the contents of install/Linux-x86_64 does not get copied because uname -p returns unknown.  Although I have not attempted to run corto under it, in cygwin uname -p returns the same.  uname -m appears to be more consistent answering the same way across ubuntu, debian, OSX and cygwin for similar hardware.

Instances of uname -p:
build/library.rb:77
build/libarary.rb:83
build/artefact.rb:34

**Comment by SanderMertens** [comment]
Good catch. I'll change this to `uname -m` which should be consistent across platforms.

**Comment by SanderMertens** [comment]
Related to #398
