### ISSUE TITLE
Corto clean recursively removes package directories

### ISSUE THREAD

**Issue by hendrenja** [cortoproject/corto#454]
Consider the following package structure:

```
/usr/local/include/corto/0.2/common/dds/factory
/usr/local/include/corto/0.2/common/dds/interface
/usr/local/include/corto/0.2/common/dds/test
```

Created by installing packages with the following names:
/common/dds/factory
/common/dds/interface
/common/dds/test

If you run `corto clean` within _/common/dds/test_, Corto will also remove _/common/dds/factory_ and _/common/dds/interface_.

**Comment by SanderMertens** [comment]
Could you post the contents of the factory, interface and test rakefiles?

**Comment by hendrenja** [comment]
/common/dds/factory
```
PACKAGE = 'common/dds/factory'

NOCORTO = TRUE

INCLUDE = ["$(CORTO_INCLUDE)"]

LANGUAGE = "c++"

require "#{ENV['CORTO_BUILD']}/package"
```

/common/dds/interface/config/adapter
```
PACKAGE = 'common/dds/interface/config/adapter'

NOCORTO = TRUE

INCLUDE = [
  "$(CORTO_INCLUDE)",
]

LANGUAGE = "c++"

require "#{ENV['CORTO_BUILD']}/package"
```

/common/dds/ddsDemo (test)

```
TARGET = 'ddsDemo'

INCLUDE = ["$(CORTO_INCLUDE)"]

LANGUAGE = "c++"

require "#{ENV['CORTO_BUILD']}/application"
```

**Comment by SanderMertens** [comment]
Numerous improvements have been made in this area. Do you still this behavior?

**Comment by wakeuky** [comment]
This issue can be closed.
