### ISSUE TITLE
Cannot resolve anything except /corto and children, cannot declare other objects

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#475]
```
cortoproject$ corto
corto shell - type 'help' for instructions.
/ $ ls  
alfie             alfie                                         /corto/core/package
corto             corto                                         /corto/core/package
jinja             jinja                                         /corto/core/package
build             build                                         /corto/core/package
  4 objects

/ $ alfie  
'alfie' does not resolve to a valid object or expression
/ $ corto  
name:         corto
parent:       /
owner:        <this>
state:        V|DCL|DEF
attributes:   S|O|P
type:         /corto/core/package
value:        {url="http://corto.io/doc/corto"}

/ $ jinja  
'jinja' does not resolve to a valid object or expression
/ $ int8 a: 1  
'int8 a: 1' does not resolve to a valid object or expression
/ $ ls  
alfie             alfie                                         /corto/core/package
corto             corto                                         /corto/core/package
jinja             jinja                                         /corto/core/package
build             build                                         /corto/core/package
  4 objects

/ $ 
```

Repo versions:

corto 640457004e919621484e09126c025c81b8457b3f
cortoproject/cortodoc@b5bc7736a013ad94abacb50a063d4926cb64ca1b
cortoproject/io@536df554317c3aa68f48bb258eaf530197a3304c
cortoproject/postgresql@8ae3ddffafdfa18f8e6773301db3fee865f32279
cortoproject/test@4db7c38644124014028a7beb2afb38b53c6a8445
cortoproject/xml@c2c875c16397a65584eff5139d65fccc0e047a7e
cortoproject/c-binding@91a49101010b791ca93627adfea20744fc84cadb
cortoproject/corto-language@01ae537645e84cb3f02dea6ca31529d40e2051e3

**Comment by jleeothon** [comment]
After removing the $HOME/.corto directory, the shell mostly appears to work. There could have been some leftover file from a faulty state of the work environment.

However, jinja can still not be resolved.

Steps:
- Build typical corto repos/package: corto, c-binding, corto-language, io, etc.
- Build web.
- Build postgresql.
- Build corto-jinja.
- Open corto shell.
- Type postgresql: works.
- Type `corto/postgresql`, `postgresql`, `web`, `corto/web`, `corto/web/server`: they are found by the shell.
- Type jinja: *is not found by the shell* (error: unresolved identifier: jinja).

**Comment by SanderMertens** [comment]
I don't think you have pushed jinja yet (the above link doesn't work). There could be a number of reasons for this behavior, most obvious one being that it is not a corto package. This is an issue that will be fixed long-term, but is not very urgent (the package can be linked with/used).
