### ISSUE TITLE
Build system option to inherit include paths from dependent packages

### ISSUE THREAD

**Issue by hendrenja** [cortoproject/corto#480]
Due to the unknown and variable header structure of third party packages, the Corto build system does not currently provide paths to headers within dependent packages. Corto anticipates the following directory structure when building using dependencies specified in .corto/packages.txt:
`<package1>/<package2>/package2.h`

Third party libraries may not support this include structure. It would be convenient if a mechanism such as the following existed:
*/foo rakefile*

`INCLUDE_PUBLIC = ["myPath/lib/dir1/dir2"]`

If /bar specified /foo in it's .corto/packages.txt file, then all public include directories for /foo ("myPath/lib/dir1/dir2") would automatically be included when building /bar.

**Comment by SanderMertens** [comment]
New versions will automatically add include paths to dependent projects. No additional configuration is required in the rakefile. A project will need to be rebuilt in order for the changes to take effect.
