### ISSUE TITLE
Make rakefile utilities more reusable

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#500]
For custom/complex rakefiles sometimes it is necessary to consume variables such as `CORTO_TARGET`, or functions like `corto_replace`. Requiring `common.rb` or `artifact.rb` is not troubleless. One concrete example is:

- I have project X and Y. From project Y, I want to consume something (A) that is located in project X's `etc` directory.
- A is to be consumed from the `rakefile` of Y's. I need a path/to/X/etc/A—which is not straightforward.

Check: 
New function in `common.rb`:  https://github.com/cortoproject/corto/blob/99ced7208e493f2eeadd9b6b97c036bfa07a9998/build/common.rb#L124
Consuming that function from a rakefile: https://github.com/cortoproject/antlr3c/blob/ec09afa171b1f69e466661530f201eeda7c06666/test/grammar/rakefile#L11

As a package maker, I want to be able to use these variables without side effects. The one file in our buildsystem that is reusable is `common.rb`. We can move functions like the one exemplified into common.rb or devise another structure.

**Comment by SanderMertens** [comment]
Please describe the usecase why you would need to manually invoke `corto_replace` or use `CORTO_TARGET`. These are buildsystem internals, and if you use them in your rakefile, you run the risk of breaking things in the future.

**Comment by SanderMertens** [comment]
I'm not happy with the changes to common.rb

The intention of this file is to just initialize buildsystem variables based on the environment / application rakefile.

Also, I want application rakefiles to be simple and declarative, and publicly exposing these functions sets the buildsystem on a slippery slope to becoming a big mess.

**Comment by SanderMertens** [comment]
I'm closing this issue as it is too open ended. If the description of the issue does not tell me when an issue is finished it's not a good description.
