### ISSUE TITLE
Improve rake sha

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#505]
As a Corto developer, I want to be able to see the status of my workspace with more verbosity:

- commit hashes (done)
- current branch (done)
- commit date (missing); useful to see how up-to-date my repos are (check `git show -s --format=%ci <commit>`)

Since the scope of the tool goes beyond hashes, we could rename it to `rake status`.

Maybe we can control verbosity with flags like:

- `rake status --hash`
- `rake status --date`
- `rake status --branch`
- Any combination of the above
- `rake status --all`
- `rake status`, by default, only hash and branch

**Comment by SanderMertens** [comment]
Please consider these changes as part of the corto tool. Also the proposed arguments don't follow rake convention (rake arguments are passed like <key>=<value>).

I don't want to build a full wrapper around the git tool. Can you explain what it is the problem you're solving?

**Comment by jleeothon** [comment]
(1) That style of arguments can be achieved by `optparse` in the standard Ruby library. You can find examples for at least three "styles" or argument passing here: http://stackoverflow.com/questions/825748/how-do-i-pass-command-line-arguments-to-a-rake-task

(2) The problem intended to solve is: «As a Corto developer, I want to be able to see the status of my workspace with more verbosity» e.g. date of commits to see easily how up-to-date or out-of-date my workspace is.

As mentioned in https://github.com/cortoproject/corto/issues/506, consider these internal tools. Maybe these two ideas should be removed altogether from the rake system since it will spread into users' installations.

**Comment by jleeothon** [comment]
This functionality has been moved to https://github.com/jleeothon/git-corto/commit/2e9649a770abeb2e923f158908c53de5bd22efca
