### ISSUE TITLE
Introduce rake update

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#506]
Consider introducing a rake task that allows updating a repository: it would be a wrapper around:

- `rake clobber`
- Verify that branch is master.
- Verify that there are no untracked changes, and that branch is up-to-date with origin/master.
- `git pull`.
- Do for any git directories in the current directory.

**Comment by SanderMertens** [comment]
Please consider these modifications as part of the corto tool. Users are not expected to use rake directly.

**Comment by jleeothon** [comment]
`rake update` wouldn't be a tool for people out there who develop with Corto. Instead it is intended to be used by the Corto core developers based on the way we have structured our workflow. Consider it as an "internal tool" of the team's.

Maybe we should consider moving both features somewhere else and not clutter what we install on users' computers with internal tools.

**Comment by jleeothon** [comment]
This functionality is tracked in https://github.com/jleeothon/git-corto/issues/1
