### ISSUE TITLE
Install gem by `pacman -S --noprogressbar --noconfirm ruby` in .drone.yml

### ISSUE THREAD

**Issue by fracting** [cortoproject/corto#516]
Hi,

Thanks for using Tea CI. I found the error `gem not found` in your build log, I think it could be solved by install ruby using pacman, please have a try.

Regards :)

**Comment by SanderMertens** [comment]
Hi Qian, thanks for the tip! Our Windows port is still a work in progress. I'll try it out soon for sure!

**Comment by SanderMertens** [comment]
@fracting I added the line to the drone.yml file, but it seems that the build is hanging on the "gem install rake" line. Do you know what could be going wrong?

**Comment by fracting** [comment]
Hmm, sorry, seems like a Wine bug, I reported as https://bugs.wine-staging.com/show_bug.cgi?id=697

Need some time to investigate...

**Comment by SanderMertens** [comment]
@fracting Did you have any time to look into this?

**Comment by fracting** [comment]
@SanderMertens I just posted some update on bug 697, you can have a look if you like.

Sorry I'm not able to dig deeper into the issue in near future because I'm preparing a immigration visa recently, but I'll get back a few months later if no body else working on it. At this time what the best we could hope is Bruno could invent some magic for us... :)

**Comment by SanderMertens** [comment]
@fracting I hope your were successful in applying for your immigration visa! Wanted to check in and see if you have been able to make any progress on this. If not, I'll temporarily disable the build (right now it's obfuscating the test results when doing PR).

**Comment by fracting** [comment]
Strangely Bruno said he can't reproduce this bug anymore: https://bugs.wine-staging.com/show_bug.cgi?id=697#c25

I don't have time to work on it soon because I'm just start my new job in Sydney, sorry for that, please temporarily disable the build and let's investigate later.

**Comment by SanderMertens** [comment]
No worries, good luck with your job in Sydney! I'm closing this issue now, if at any point somebody is resuming work on this project please do not hesitate to reach out.

Thanks for the help!
