### ISSUE TITLE
Improve and complete corto_ll API

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#525]
## Pointer-comparison vs value-comparison functions

`corto_ll` includes `corto_llFind` and `corto_llHasObject`, which are different in that one takes a comparison function while the other makes a pointer comparison.

It would be as well useful to have similar pairs of functions for `corto_llRemove` and `corto_llReplace`, and double-check if the API is missing others that fall in the same possibility.

## Complete the C-binding

Functions like the above mentioned are missing from the API, this makes it hard to use them on other types because manual value copying or reference counting must be made.

**Comment by SanderMertens** [comment]
Issue is not specific, and suggested function is redundant.
