### ISSUE TITLE
Unimplemented tests appear both as passing and failing

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#526]
A test that is not implemented (i.e. does no assertions) appears both as failing and passing:

<img width="432" alt="screenshot 2016-08-01 22 50 16" src="https://cloud.githubusercontent.com/assets/6202537/17308460/6b7c89c8-583a-11e6-9022-146ceeca2ac6.png">

**Comment by jleeothon** [comment]
Appears to not be an issue solely with unimplemented tests; tests with failing assertions display the same bug.

**Comment by jleeothon** [comment]
Hashes:

cortoproject/c-binding@892174f
cortoproject/corto@97cd971
cortoproject/test@6904a48

**Comment by SanderMertens** [comment]
Issue has been fixed in test framework.
