### ISSUE TITLE
Rename functions that return collection length to "length" instead of "size"

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#527]
The generate functions *listSize and *seqSize are unrelated despite the resemblance in name.

Expected behavior:

Both function would return the number of elements in the collection.

Actual behavior:

*listSize returns the number of elements in a list, whereas *seqSize resizes the sequence.

**Comment by SanderMertens** [comment]
We should rename the `Size` methods to `Length` which is similar to JavaScript and Java.

This affects the `corto_ll_size`, `corto_rbtree_size` functions as well as the functions generated by `cortoproject/c-binding` in `api/src/apicollection.c`

**Comment by SanderMertens** [comment]
This has been addressed in v2.0 API redesign. Ultimately `count` has been used for functions that return the number of elements in a collection, where the `size` function to change the number of elements in a collection has been renamed to `resize`.
