### ISSUE TITLE
Virtual method of BaseVisitor/TestVisitor cannot be resolved

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#529]
**Investigate further**

The `BaseVisitor` found in [parser.xml](https://github.com/cortoproject/corto-parser/blob/915045e8d51e5d899c97f3d715c9bc1c3ba8cc0c/parser.xml) generates a problematic signature for virtual method resolution.

The lines in parser's `_wrapper.c`:

```
if (!_methodId) {
    _methodId = corto_interface_resolveMethodId(_abstract, "visit(BaseVisitor visitor)");
}
```

Cannot be resolved for a [TestVisitor](https://github.com/cortoproject/corto-parser/blob/dea9a556a499ddbcbf5f55bc874775a8dde42680/test/visitor/test.cx) instance.

If we manually changed the generated wrapper to try to resolve a more correct name i.e. `"visit(parser/BaseVisitor visitor)"` or `"visit(corto/parser/BaseVisitor visitor)"` or `"visit(/corto/parser/BaseVisitor visitor)"`, then the method resolution works.

**Comment by SanderMertens** [comment]
The way virtual methods are invoked has now changed, which should have addressed this issue. Issues with the new method will be captured on a new ticket.

The new method stores the method id on the method object, and then directly looks up the correct method in the method table of the type of the object the method is invoked on.

For example, to invoke overridable method `point/add` on an object of type `point3d`, it would do (pseudo code):

`corto_invoke(point3d->methods[point_add_o->id], ...`
