### ISSUE TITLE
error in `corto create myApp`

### ISSUE THREAD

**Issue by KrishnaPG** [cortoproject/corto#536]
After fresh installation of `corto`, following the tutorial steps ([here](https://www.corto.io/tutorial_1.html)), the create command failed as below:
````
$ corto create myApp
corto:  create application 'myApp'
corto: failed to start process 'rake'
````
The `myApp` folder is created fine. Looks like the `corto run` command is looking for `rake` which is not found.

I thought `rake` was required only for building the `corto` itself and not the user projects?

Anyway, if `rake` is indeed required for `corto run`, then I think letting ` curl https://corto.io/install | sh` command install it as prerequisite would be good idea as part of the `corto` installation itself (rather than user having to install it separately).

**Comment by KrishnaPG** [comment]
After installing `rake` with the command `sudo apt-get install rake`, the `corto run` command worked fine. It printed the output.

**Comment by SanderMertens** [comment]
@KrishnaPG ah, the documentation should be clearer about that. The `corto create` tool uses the rake-based buildsystem. It is a simple wrapper around creating a corto project that helps you to setup a project very quickly.

It is possible to setup a project with another buildsystem manually, but then the `corto create` tool won't work. Essentially for a non-rake based project, you would need to manually link with libcorto.so and include the package repository:

gcc src/myApp.c -I/usr/local/include/corto/0.2 /usr/local/lib/corto/0.2/corto/libcorto.so -o myApp

**Comment by KrishnaPG** [comment]
Thanks @SanderMertens No issues. Just thought of suggesting to add the `rake dependency` to the `corto installation` step itself. Will help the beginners.
