### ISSUE TITLE
Enable routing of hierarchical requests in mount

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#541]
When mounts expose a hierchical structure, it can be a lot of work to parse a request and map it to the structure of the datasource. For example, to correctly handle the following requests

``` c
parent = "foo", expr = "*"
parent = "foo/bar", expr = "*"
```

the `onRequest` method has to parse the `parent` string, split it up into its different elements, then match those elements to the actual source of the data. This is a lot of overhead for a task that is common for many mounts.

To make this process easier, a new class called `core/router` will be introduced. The functionality of a router will be analogous to routers found in web frameworks, where a URL (often hierarchical) is matched against a number of "routes", which specify an expression.

An example of what the routes for the above requests could look like:

```
route foo: "foo/:foo_id"
route bar: "foo/:foo_id/:bar_id"
```

The router will evaluate all route expressions, and picks the route that matches the most elements. A route will be a `procedure` that inherits from `method`. The parameters of the procedure will be determined by the number of variables in the expression. For example, the above routes will result in the following functions:

``` c
string foo(corto_string foo_id);
string bar(corto_string foo_id, corto_string bar_id);
```

A mount will inherit from the `core/router` class and by default the `onRequest` method will forward a request to the router class, which will then invoke the correct route.

Other packages may also benefit from the router class, for example the web package could use the router to route HTTP requests to the appropriate handlers. Specializations of the `core/route` type are also possible, for example, a route could automatically forward all variables in the route expression to a `corto/t` template and return the result.

**Comment by jleeothon** [comment]
A `route` now also supports a custom parameter through `paramType` and `paramName`. This can be used for data inherent to the use case e.g. web routes, this is the HTTP request.

**Comment by SanderMertens** [comment]
Feature is implemented, only thing left to add is testcases.
