### ISSUE TITLE
Support custom logger handlers

### ISSUE THREAD

**Issue by hendrenja** [cortoproject/corto#563]
The ability to register a callback/handler for Corto logging messages would provide a nice feature for consumers to route Corto log messages to their own logging facility. 

```
void MyLoggerHandler(const char *message)
{
    FooLogger logger;
    logger.log(message);
}

corto_logger_register_handler(&MyLoggerHandler)
```

`corto_logger_register_handler()` should be globally define a handler for all Corto log messages.

**Comment by SanderMertens** [comment]
This feature has been implemented.
