### ISSUE TITLE
Extend contentType API

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#565]
Currently the Content Type API supports operations such as `fromCorto`, `toCorto`.

For sake of completion, we would like to support different signatures that include e.g. whether or not a brand new object is created or if the content is written unto an existing object.

(In the following example, for `json`) Namely:

```C
corto_int16 json_toObject(corto_object* o, corto_string content)
corto_string json_fromObject(corto_object o)
corto_int16 json_toValue(corto_value* v, corto_string content)
corto_string json_fromValue(corto_value v)
```

**Comment by SanderMertens** [comment]
This issue has been implemented.
