### ISSUE TITLE
CI tests for /corto/web not running correctly

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#576]
Normally, `corto test` or `rake test` will traverse subdirectories, find `test` directories and run tests. This does not occur in `/corto/web` as of https://github.com/cortoproject/web/commit/8e898501d55802676b0844f660c9a514d43704ff

Example CI build:

- https://travis-ci.org/cortoproject/web/builds/183065828

**Comment by SanderMertens** [comment]
Looks like tests are running again ;-) next time it's better to create this issue in the repository where the issue is occurring.
