### ISSUE TITLE
Build does not error when `corto/fmt/json` is missing

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#577]
The build process should exit non-zero when `corto/fmt/json` isn't  found and thence a rakefile cannot be generated.

This would produce an earlier exit and make errors more obvious in the future. This is an example where the build exited successfully:

https://travis-ci.org/cortoproject/corto-parser/builds/185683570

Note, during the "install" step in Travis, the script would stop execution altogether if one command returns non-zero.

**Comment by SanderMertens** [comment]
This issue has been addressed. A build will now fail when `corto/fmt/json` cannot be found.
