### ISSUE TITLE
Add blessing to keep code bug free.

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#582]
Please consider adding this along the source code: https://gist.github.com/jleeothon/0239094a1b3e495cd2d0cfe00765d1d4

**Comment by SanderMertens** [comment]
Please make a pull request for this so we can properly review it.

**Comment by SanderMertens** [comment]
Not sure if this will ever get merged... but I'll keep the PR open to not miss out on any of the potential benefits =]
