### ISSUE TITLE
Consider linking build directory instead a of copying

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#589]
One of the steps of `corto/configure` is to `cp` the `build` directory. This makes it difficult to test changes to the `build` directory because it becomes necessary to `source` the script every time. 

Sourcing the script is not an idempotent operation because e.g. `PATH` and `LD_LIBRARY_PATH` become bloated (this is probably harmless but undesirable).

To avoid sourcing the script every time, can we consider linking this directory?

**Comment by SanderMertens** [comment]
I don't see any problems with that. Sounds good.
