### ISSUE TITLE
configure does not work with fish shell

### ISSUE THREAD

**Issue by Dynamic-Gravity** [cortoproject/corto#611]
```
configure (line 7): 'case' builtin not inside of switch block
case $CURRENT_SHELL in
^
from sourcing file configure
        called on standard input
```
Call it with bash and it works just fine.

Is it possible to make the script for different shells, or is this going to remain solely for bash?

**Comment by SanderMertens** [comment]
I am not familiar with the fish shell, but if it can be made to work with different shells that would be great!

If you know how the same or similar functionality can be achieved with fish shell, just create a PR and I'll merge it.

**Comment by Dynamic-Gravity** [comment]
@SanderMertens alright I'll get to work on it. :)

**Comment by SanderMertens** [comment]
The new buildsystem no longer requires using a `configure` script, so I'm closing this issue.
