### ISSUE TITLE
Standardize header file variables

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#82]
I've noticed that the variables for header definitions are a mix of uppercase and lowercase across the project. Also, some may or may not include the same prefix as in the filename ("db" or "core").

A related issue is: what will be the prefix for the core? "db"? "core"? "hyve"? etc.?

Let's standardize it:
- They are all caps.
- They all start with the prefix *prefix goes here*, followed by an underscore, i.e. ("DB_").
- They end with an underscore followed by an "H" ("_H").
- The variable is the same as the filename, including the prefix, but except for the trailing "_H", which represents the file extension.

**Comment by jleeothon** [comment]
I see that many files with generated code do have a mixed-case name, e.g. cx_collection.h or cx_constant.h. Should we leave it such?

**Comment by SanderMertens** [comment]
This issue has been resolved as part of #424
